In [5]:
import dotenv
import psycopg2
import pandas as pd
import os
from dotenv import load_dotenv
load_dotenv()

OUTPUT_DIR = "./export_supabase/vtc_test"

In [7]:
driver_reviews = pd.read_csv(f"{OUTPUT_DIR}/driver_reviews.csv")
locations = pd.read_csv(f"{OUTPUT_DIR}/locations.csv")
payments = pd.read_csv(f"{OUTPUT_DIR}/payments.csv")
promotions = pd.read_csv(f"{OUTPUT_DIR}/promotions.csv")
rides = pd.read_csv(f"{OUTPUT_DIR}/rides.csv")
users = pd.read_csv(f"{OUTPUT_DIR}/users.csv")
vehicles = pd.read_csv(f"{OUTPUT_DIR}/vehicles.csv")

print("Lenght driver_reviews:", len(driver_reviews))
print("Lenght locations:", len(locations))
print("Lenght payments:", len(payments))
print("Lenght promotions:", len(promotions))
print("Lenght rides:", len(rides))
print("Lenght users:", len(users))
print("Lenght vehicles:", len(vehicles))

Lenght driver_reviews: 2
Lenght locations: 2
Lenght payments: 2
Lenght promotions: 2
Lenght rides: 2
Lenght users: 4
Lenght vehicles: 2

In [8]:
driver_reviews.head()

,id,driver_id,customer_id,rating,comment,review_date
0,1,2,1,5.0,"Great ride, very friendly driver!",2026-04-20 20:08:45.897727+00:00
1,2,4,3,4.5,"Smooth ride, but the car was a bit messy.",2026-04-20 20:08:45.897727+00:00

In [9]:
locations.head()

   id                     address  latitude  longitude
0   1   123 Main St, Anytown, USA   40.7128   -74.0060
1   2  456 Elm St, Othertown, USA   34.0522  -118.2437

In [10]:
payments.head()

,id,ride_id,amount,payment_method,payment_time,transaction_id
0,1,1,25.0,credit card,2026-04-20 20:08:45.897727+00:00,TXN123456
1,2,2,30.0,paypal,2026-04-20 20:08:45.897727+00:00,TXN789012

In [11]:
promotions.head()

,id,code,description,discount_percentage,valid_from,valid_to
0,1,WELCOME10,10% off for new users,10.0,2023-09-01,2023-12-31
1,2,SAVE20,20% off on rides over $50,20.0,2023-10-01,2023-11-30

In [12]:
rides.head()

,id,customer_id,driver_id,vehicle_id,pickup_location_id,dropoff_location_id,start_time,end_time,status,distance,fare
0,1,1,2,1,1,2,2023-10-01 08:00:00+00:00,2023-10-01 08:30:00+00:00,completed,15.5,25.0
1,2,3,4,2,2,1,2023-10-02 09:00:00+00:00,2023-10-02 09:45:00+00:00,completed,20.0,30.0

In [13]:
users.head()

,id,name,email,phone_number,user_type,created_at,rating,profile_picture
0,1,Alice Johnson,alice@example.com,123-456-7890,customer,2026-04-20 20:08:45.897727+00:00,4.5,alice.jpg
1,2,Bob Smith,bob@example.com,234-567-8901,driver,2026-04-20 20:08:45.897727+00:00,4.8,bob.jpg
2,3,Charlie Brown,charlie@example.com,345-678-9012,customer,2026-04-20 20:08:45.897727+00:00,4.2,charlie.jpg
3,4,David Wilson,david@example.com,456-789-0123,driver,2026-04-20 20:08:45.897727+00:00,4.9,david.jpg

In [14]:
vehicles.head()

   id  driver_id    make    model  year license_plate color insurance_expiry
0   1          2  Toyota  Corolla  2018        ABC123  Blue       2024-05-01
1   2          4   Honda    Civic  2020        XYZ789   Red       2025-08-15